### ISSUE TITLE
Keep a counter of the number of times the "Install calendar extension" pop-up is shown

### ISSUE THREAD

**Issue by mrose17** [brave/brave-talk#251] opened 2022-04-13 13:59 UTC
After 3 times, set `extension_promo_dismissed` to `true`

**Comment by hadiamjad** [comment] 2022-05-27 19:44
Currently, the extension pop-up (reference image attach) appears, and if the user crosses(x) the pop-up it never appears again.

**Update:** 
Now, we updated this case scenario and now we maintain a counter `extension_promo_dismissed` in local storage. 

if the user crosses(x) the pop-up or clicks the `Start free call` button without crossing the pop-up this counter `extension_promo_dismissed` is incremented. And if either of these actions are performed greater than 3 i.e `extension_promo_dismissed > 3`,  then the pop-up never appears again. 
 
For example:
When you can cross this pop-up or clicks the `Start free call` button,  in the local storage counter `extension_promo_dismissed` will be incremented. You can refresh the page and a pop-up will appear again because `extension_promo_dismissed < 3`. You can repeat this process until it becomes `extension_promo_dismissed > 3` and its value is set to `true`.


![Screen Shot 2022-05-18 at 6 00 04 PM](https://user-images.githubusercontent.com/46374292/170777774-755385c8-093e-4e29-9118-a45d416fe1ea.png)

**Comment by stephendonner** [comment] 2022-05-27 21:24
## Verified `PASSED` using 

Brave | 1.39.111 Chromium: 102.0.5005.61 (Official Build) (x86_64)
-- | --
Revision | 0e59bcc00cc4985ce39ad31c150065f159d95ad3-refs/branch-heads/5005@{#819}
OS | macOS Version 11.6.6 (Build 20G624)

### Steps:
1. installed `1.39.111`
2. launched Brave
3. loaded `talk.brave.software`
4. opened `Developer Tools`
5. clicked on the `Application` panel
6. clicked on the `Local Storage` entry for `talk.brave.software`
7. confirmed no entries/values, yet
8. confirmed I saw and clicked on the `Install Calendar extension` button on the lower-right dialog
9. reloaded the tab
10. confirmed the `Local Storage` entry now had an `extension_promo_dismissed` entry, with no value
11. reloaded the tab
12. confirmed `extension_promo_dismissed` was now `1`
13. dismissed the `Install Calendar extension` dialog via its `X` close widget
14. reloaded the tab
15. confirmed `extension_promo_dismissed` was now `2`
16. reloaded the tab
17. dismissed the `Install Calendar extension` dialog by clicking on the `Install Calendar extension` button
18. reloaded the tab
19. confirmed `extension_promo_dismissed` was now `3`
20. reloaded the tab
21. confirmed `Install Calendar extension` dialog still appears
22. dismissed it via one of the above methods
23. reloaded the tab
24. confirmed `extension_promo_dismissed` was now `true`
25. confirmed the `Install Calendar extension` dialog no longer appears
26. reloaded the tab a few more times, confirmed it didn't re-appear

initial state | 1st dismissal | 2nd dismissal | 3rd dismissal | final state
----------------|------------------|--------------------|-------------------|--------------
<img width="1312" alt="Screen Shot 2022-05-27 at 2 04 33 PM" src="https://user-images.githubusercontent.com/387249/170790981-e7579cca-0ed2-412b-ab67-c694b6a1fbab.png"> | <img width="1312" alt="Screen Shot 2022-05-27 at 2 07 00 PM" src="https://user-images.githubusercontent.com/387249/170790986-3bd37edd-7868-4103-a7a2-4c79cbdc921a.png"> | <img width="1312" alt="Screen Shot 2022-05-27 at 2 07 24 PM" src="https://user-images.githubusercontent.com/387249/170790990-0e9016e4-10aa-4111-af87-b7bb308861f4.png"> | <img width="1312" alt="Screen Shot 2022-05-27 at 2 07 36 PM" src="https://user-images.githubusercontent.com/387249/170790991-f0d45c12-4ea8-4763-8d2a-f36ff4941f05.png"> | <img width="1312" alt="Screen Shot 2022-05-27 at 2 07 58 PM" src="https://user-images.githubusercontent.com/387249/170790994-894866d6-63ab-4cad-b10d-bbc7b7846dd7.png"> | <img width="1312" alt="Screen Shot 2022-05-27 at 2 07 58 PM" src="https://user-images.githubusercontent.com/387249/170791138-460d90eb-3588-4915-a97e-cf693cd72bc9.png">

**Closed** 2022-06-09 11:47 UTC
Labels: P3
