### ISSUE TITLE
Switching accounts causes wallet address to show as 0

### ISSUE THREAD

**Issue by srirambv** [brave/brave-talk#903] opened 2023-05-16 04:28 UTC
### Description
Switching accounts causes wallet address to show as 0

### Steps
1. Create a Web3 call on talk.brave.com
2. Connect a different wallet to join the call
3. Open wallet panel and select connect 
4. Switch accounts from the one that is connected
5. Webpage shows `Your wallet address 0` 

### Actual Result

https://github.com/brave/brave-talk/assets/17010094/47164a91-ebb4-49ef-ac24-223700f3c56d

### Expected Result
Should update address similar to Desktop

https://github.com/brave/brave-talk/assets/17010094/ae9b7feb-2977-4d14-884b-242c2045c954

### Additional Information
Seems iOS specific. Android behaviour is similar to Desktop

cc: @mrose17 @johnhalbert @StephenHeaps @nuo-xu

**Comment by StephenHeaps** [comment] 2023-05-16 13:30
This looks like an iOS issue with the `accountsChanged` event. Checking brave-talk, we are [expecting the accounts to be emitted as an array](https://github.com/brave/brave-talk/blob/main/src/hooks/use-web3-call-state.ts#L48-L51) and the [provider docs](https://docs.metamask.io/wallet/reference/provider-api/#accountschanged) mention an array but iOS appears to be just [providing the account address String (not in an array)](https://github.com/brave/brave-ios/blob/development/Sources/Brave/Wallet/WalletProviderConstants.swift#L30).

I believe this should be resolved with https://github.com/brave/brave-ios/issues/7463.

**Comment by StephenHeaps** [comment] 2023-05-16 21:56
I can confirm the above; this will be fixed with https://github.com/brave/brave-ios/issues/7463. Currently targeting v1.52 for the fix. Thanks for the tag @srirambv 👍.

https://github.com/brave/brave-talk/assets/5314553/5c38e4e9-ca91-4c6f-913a-adc6dd9ea67b

**Closed** 2023-05-26 16:53 UTC
Labels: ui, wallet-support, web3, iOS
